version: '3.7'

services:
    db:
        container_name: db
        image: mysql
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--default-authentication-plugin=mysql_native_password'
            ]
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - smart-home
        environment:
            MYSQL_DATABASE: smart_home
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        container_name: php
        build:
            context: .
            dockerfile: php/Dockerfile-php
        ports:
            - "9001"
        volumes:
            - ./smart-home/:/var/www/smart-home
        networks:
            - smart-home
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://symfony:symfony@localhost:3306/smart_home?serverVersion=5.7
            JWT_PASSPHRASE: localhost
            JWT_TTL: 9993600
            MQTT_SERVER_HOST: 127.0.0.1
            MQTT_SERVER_PORT: 1883
            MQTT_CLIENT_ID: smarthome-core
        depends_on:
            - db
    vue:
        container_name: vue
        build:
            context: .
            dockerfile: vue/Dockerfile-vue
        volumes:
            - ./smart-home-frontend/:/var/www/smart-home-frontend
        networks:
            - smart-home
        environment:
            VUE_APP_BASE_URL: http://localhost:8002/api
        depends_on:
            - php
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile-nginx
        volumes:
            - ./smart-home/:/var/www/smart-home
            - ./smart-home-frontend/:/var/www/smart-home-frontend
        ports:
            - 8001:80
            - 8002:8080
        networks:
            - smart-home
        depends_on:
            - vue


networks:
    smart-home:
