version: '3.7'

services:
    mqtt:
        container_name: mqtt
        restart: always
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 9002:9001
        networks:
            - smart-home
        volumes:
            - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    db:
        container_name: db
        image: mysql
        restart: always
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--default-authentication-plugin=mysql_native_password'
        ]
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - smart-home
        environment:
            MYSQL_DATABASE: smart_home
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        depends_on:
            - mqtt
    php:
        container_name: php
        restart: always
        build:
            context: .
            dockerfile: php/Dockerfile-php
        ports:
            - "9001"
        volumes:
            - ./smart-home/:/var/www/smart-home
        networks:
            - smart-home
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://symfony:symfony@db:3306/smart_home?serverVersion=5.7
            JWT_PASSPHRASE: localhost
            JWT_TTL: 9993600
            MQTT_SERVER_HOST: 127.0.0.1
            MQTT_SERVER_PORT: 1883
            MQTT_CLIENT_ID: smarthome-core
        depends_on:
            - db
    node:
        container_name: node
        restart: always
        build:
            context: .
            dockerfile: node/Dockerfile-node
        networks:
            - smart-home
        depends_on:
            - php
    nginx:
        container_name: nginx
        restart: always
        build:
            context: .
            dockerfile: nginx/Dockerfile-nginx
        volumes:
            - ./smart-home/:/var/www/smart-home
        ports:
            - 8001:80
            - 8002:8080
        networks:
            - smart-home
        environment:
            VUE_APP_BASE_URL: http://core.smarthome.lan:8001/api
        depends_on:
            - node


networks:
    smart-home:
