FROM node:latest as build-stage

COPY smart-home-frontend/ /var/www/smart-home-frontend

WORKDIR /var/www/smart-home-frontend

RUN npm install
RUN npm run build


FROM nginx:latest

COPY nginx/nginx.conf /etc/nginx/
COPY nginx/default.conf /etc/nginx/conf.d/
COPY nginx/vue.conf /etc/nginx/conf.d/

RUN echo "upstream php-upstream { server php:9001; }" > /etc/nginx/conf.d/upstream.conf

CMD ["nginx"]

EXPOSE 80
EXPOSE 8080
EXPOSE 443