FROM node:latest as build-stage

WORKDIR smart-home-frontend/
CMD pwd
COPY package.json /var/www/smart-home-frontend
RUN npm install
COPY ./ /var/www/smart-home-frontend
RUN npm run build

FROM nginx:latest as production-stage

RUN mkdir /app
COPY --from=build-stage /smart-home-frontend/dist /var/www/smart-home-frontend

COPY nginx/nginx.conf /etc/nginx/
COPY nginx/default.conf /etc/nginx/conf.d/
COPY nginx/vue.conf /etc/nginx/conf.d/

RUN echo "upstream php-upstream { server php:9001; }" > /etc/nginx/conf.d/upstream.conf

CMD ["nginx"]

EXPOSE 80
EXPOSE 8080
EXPOSE 443