FROM node:latest

WORKDIR /var/www/smart-home-mqtt-pipe

COPY smart-home-mqtt-pipe/package*.json /var/www/smart-home-mqtt-pipe/

RUN npm install

COPY smart-home-mqtt-pipe/ /var/www/smart-home-mqtt-pipe

RUN npm run build

EXPOSE 8080
CMD ["node", "dist/Index.js"]