name: Continuous Integration
on:
  push:
    branches:
      - 'master'

jobs:
   checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: echo ${{secrets.DEPLOY_PASSWORD}} | sudo chown -R $USER:$USER ~/Runners/_work
      - name: Git checkout
        uses: actions/checkout@v2.1.1
      - name: Composer Install
        uses: nick-zh/composer@php7.4
        with:
          action: 'install --ignore-platform-reqs'
      - name: Database Init
        uses: nick-zh/composer@php7.4
        with:
          action: 'db:init'

