name: Continuous Integration
on:
  push:
    branches:
      - 'master'

jobs:
   checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: echo ${{secrets.DEPLOY_PASSWORD}} | sudo chown -R $USER:$USER ~/Runners/_work
      - name: Git checkout
        uses: actions/checkout@v2.1.1
      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Build the stack
        run: docker-compose -f docker-compose.yml ps


