name: Continuous Integration
on:
  push:
    branches:
      - 'master'

jobs:
   checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Fix permissions
        run: echo ${{secrets.DEPLOY_PASSWORD}} | sudo chown -R $USER:$USER ~/Runners/leviathan/_work
      - name: Checkout Leviathan
        uses: actions/checkout@v2.1.1
      - name: Checkout SmartHome project
        uses: actions/checkout@v2.1.1
        with:
          repository: ilesar/smart-home
      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Running containers...
        run: docker-compose -f docker-compose.yml ps


