name: Continuous Integration
on:
  push:
    branches:
      - 'master'

jobs:
   checkout:
    name: Checkout
    runs-on: self-hosted
    steps:
      - name: Git 2FA
        run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - name: Checkout Leviathan
        uses: actions/checkout@v2.2.0
      - name: Checkout SmartHome project
        uses: actions/checkout@v2.2.0
        with:
          repository: ilesar/smart-home
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./smart-home
      - name: Checkout SmartHomeFrontend project
        uses: actions/checkout@v2.2.0
        with:
          repository: ilesar/smart-home-frontend
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./smart-home-frontend
      - name: Current directory
        run: pwd
      - name: Build the stack
        run: docker-compose up -d
      - name: Running containers...
        run: docker-compose ps


